# 06. Funciones principales de NumPy

### Importando librerías

In [1]:
import numpy as np

In [27]:
arr = np.random.randint(1,20,10)

In [28]:
matriz = arr.reshape(2,5)
matriz

array([[14,  7,  2, 19,  8],
       [12,  9, 10, 16,  7]])

In [29]:
arr

array([14,  7,  2, 19,  8, 12,  9, 10, 16,  7])

### Max

In [30]:
arr.max()

19

In [40]:
matriz

array([[14,  7,  2, 19,  8],
       [12,  9, 10, 16,  7]])

In [41]:
#matriz.max(1) # Fila
matriz.max(0) # Columna
# Podemos regresar los máximos de cada fila o columna especificando el eje.

array([14,  9, 10, 19,  8])

### Argmax

In [42]:
arr.argmax() # Indica el índice del número mayor

3

In [9]:
matriz.argmax(0) # Tambien tenemos .argmax() que nos devuelve la posición del elemento

array([1, 0, 1, 0, 1])

### Min

In [10]:
arr.min() # Indica el valor más pequeño del arry

2

In [11]:
matriz.min(0)

array([12,  3,  5,  2,  5])

### Argmin

In [43]:
arr.argmin()

2

In [13]:
matriz.argmin(1)

array([2, 3])

### Ptp

In [44]:
arr

array([14,  7,  2, 19,  8, 12,  9, 10, 16,  7])

In [45]:
arr.ptp() # Pick to Pick. Podemos saber la diferencia de valor más bajo con el más alto.

17

In [16]:
matriz.ptp(0)

array([ 4, 12, 14,  7,  7])

### Sort

In [46]:
arr.sort() # Ordena de menor a mayor los números del arreglo
arr

array([ 2,  7,  7,  8,  9, 10, 12, 14, 16, 19])

### Percentile

In [47]:
np.percentile(arr,50)

9.5

### Median

In [19]:
np.median(arr) # La mediana de un arreglo. Que significa el percentil 50, donde se encuentra la mitad del array

10.5

In [20]:
np.median(matriz,1) # La mediana por el eje (1 ó 0)

array([ 5., 15.])

### Standard Deviation (std)

In [21]:
np.std(arr) ** 2

31.360000000000007

### Variance (Var)

In [22]:
np.var(arr)

31.360000000000003

### Mean

In [48]:
np.mean(arr) # La media, es la operación de la suma de todo los operadores del array dividido la cantidad de valores que tiene

10.4

### Concatenate

In [51]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [50]:
np.concatenate((a,b),axis=0) # Se concatena una tupla por el eje 0
# El error es debido a que "a" tiene 2 dimensiones mientras que "b" tiene 1.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
a.ndim
b.ndim

1

In [53]:
b = np.expand_dims(b,axis=0)

In [54]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([[5, 6]])

In [55]:
np.concatenate((a,b),axis=1)
# Como "b" es una fila y no una columna, no se puede concatenar a menos que se aplique la Tanspuesta (T).

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [56]:
np.concatenate((a,b.T),axis=1) # Se aplica la Transpuesta de una matriz (T)

array([[1, 2, 5],
       [3, 4, 6]])

### Transpuesta

In [57]:
b.T

array([[5],
       [6]])