
# 02. Tipos de datos
Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

### Importando librerias

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr.dtype # Si queremos usar otro tipo de dato lo podemos definir en la declaración del array.

dtype('int64')

In [3]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype # Ahora vemos que los valores están con punto decimal.

dtype('float64')

In [4]:
arr # Si ya se tiene el array definido se usa el método .astype() para convertir el tipo de dato.

array([1., 2., 3., 4.])

In [5]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr # También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.

array([1., 2., 3., 4.])

### Cambiando tipo de datos

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr # También podemos convertir los datos en tipo string.

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr # De igual forma se puede pasar de string a numero.

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [6]:
arr = np.array(['hola','1','2','3','4'])
arr = arr.astype(np.int8)
arr # Si un elemento no es de tipo número el método falla.'''

ValueError: invalid literal for int() with base 10: 'hola'