# 05. 🟦🔹Shape y Reshape
- Shape   => Me indica la forma del arreglo
- Reshape => Transforma el arreglo mientras se mantengan los elementos.

### Importar librerías

In [19]:
import numpy as np 

In [20]:
arr = np.random.randint(1,10,(3,2)) # Array de 1 a 10 con una estructura de 3 x 2

### Shape

In [21]:
arr.shape # Indica la cantidad de filas y columnas. Muy útil para saber que tan grande es el arreglo que se está trabajando.

(3, 2)

In [22]:
arr

array([[6, 7],
       [4, 7],
       [2, 7]])

### Reshape

In [23]:
arr.reshape(1,6) # Comando para cambiar la forma establecida en un array

array([[6, 7, 4, 7, 2, 7]])

In [24]:
arr.reshape(2,3)

array([[6, 7, 4],
       [7, 2, 7]])

In [25]:
np.reshape(arr,(1,6))

array([[6, 7, 4, 7, 2, 7]])

In [26]:
arr

array([[6, 7],
       [4, 7],
       [2, 7]])

In [27]:
np.reshape(arr,(2,3),'C') # Se puede hacer un reshape como lo haría en el lengaje de C.

array([[6, 7, 4],
       [7, 2, 7]])

In [28]:
np.reshape(arr,(2,3),'F') # Se puede hacer un reshape como lo haría en el lengaje de Fortran.

array([[6, 2, 7],
       [4, 7, 7]])

In [29]:
np.reshape(arr,(2,3),'A') # Además existe la opción de hacer reshape según como esté optimizado el guardado de datos en memoría del sistema. En este caso es como en C.

array([[6, 7, 4],
       [7, 2, 7]])